#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
  remove)
	#
	# Restore /etc/resolv.conf if it's resolvconf symlink
	#
	if \
		[ -L /etc/resolv.conf ] \
		&& { \
			[ "$(readlink /etc/resolv.conf)" = "/etc/resolvconf/run/resolv.conf" ] \
			|| [ "$(readlink /etc/resolv.conf)" = "resolvconf/run/resolv.conf" ] ; \
		}
	then
		rm -f /etc/resolv.conf
		if [ -e /etc/resolvconf/run/resolv.conf ] ; then
			mv -f /etc/resolvconf/run/resolv.conf /etc/resolv.conf
		elif [ -e /etc/resolvconf/resolv.conf.d/original ] ; then
			mv -f /etc/resolvconf/resolv.conf.d/original /etc/resolv.conf
		fi
	fi
	;;
  purge)
	if [ -L /etc/resolvconf/run ] ; then
		rm -f /etc/resolvconf/run
	elif [ -d /etc/resolvconf/run ] ; then
		rm -rf /etc/resolvconf/run
	fi
	rm -f /etc/resolvconf/resolv.conf.d/tail
	rm -f /etc/resolvconf/resolv.conf.d/original
	rm -f /etc/default/resolvconf
	rmdir /lib/init/rw/resolvconf/interface || :
	rmdir /lib/init/rw/resolvconf || :
	;;
  # disappear|upgrade)
	# Don't do anything
	# ;;
  # failed-upgrade)
	# Don't do anything because we don't do anything in the postrm on upgrade
	# ;;
  # abort-install|abort-upgrade)
	# Don't do anything.  In the preinst we create directories
	# but there is no need to remove them.
	# ;;
esac

