#!/bin/sh

set -e

. /usr/share/debconf/confmodule

MYNAME=resolvconf.preinst
report() { echo "${MYNAME}: $*" ; }
report_err() { report "Error: $*" >&2 ; }
report_info() { report "Info: $*" >&2 ; }

standard_run_available() {
	[ -d /run ] \
	&& [ -w /run ] \
	&& [ -r /proc/mounts ] \
	&& grep -qs "^tmpfs[[:space:]]\+/run[[:space:]]\+tmpfs[[:space:]]\+\([^[:space:]]\+,\)\?rw" /proc/mounts
}

standard_run_subdirs_exist_or_create() {
	{ [ -d /run/resolvconf ] || mkdir -v /run/resolvconf ; } \
	&& { [ -d /run/resolvconf/interface ] || mkdir -v /run/resolvconf/interface ; }
}

### Create /etc/resolvconf/run ###
#
# We create the directories here, in the preinst, so that if resolvconf
# is run before the postinst runs there is nevertheless a place for
# resolvconf to store data.  (The latter can occur if resolvconf is
# installed simultaneously with a caching nameserver package whose
# postinst runs resolvconf to add "nameserver 127.0.0.1".)
#
case "$1" in
  install|upgrade)
	# If it's not canonicalizable then delete it, otherwise if it's standard then migrate it
	if [ -L /etc/resolvconf/run ] ; then
		RUN_CANONICALPATH="$(readlink -f /etc/resolvconf/run || :)"
		if [ -z "$RUN_CANONICALPATH" ] ; then
			# It's not canonicalizable
			report_err "Deleting /etc/resolvconf/run symlink whose canonical path could not be determined"
			rm -f /etc/resolvconf/run
		else
			# It's canonicalizable
			[ "$RUN_CANONICALPATH" = "/lib/init/rw/resolvconf" ] \
			&& standard_run_available \
			&& standard_run_subdirs_exist_or_create \
			&& { 
				{ 
					F="$(echo /lib/init/rw/resolvconf/*)" \
					&& [ "$F" ] \
					&& [ "$F" != '/lib/init/rw/resolvconf/*' ] \
					&& cp -a /lib/init/rw/resolvconf/* /run/resolvconf \
					&& report_info "Migrated run-time database from /lib/init/rw/resolvconf to /run/resolvconf"
				}
				ln -nsf /run/resolvconf /etc/resolvconf/run \
				&& report_info "Pointed /etc/resolvconf/run to /run/resolvconf"
			}
		fi
	fi
	# Delete it if it isn't a directory or a link to one
	if [ -e /etc/resolvconf/run ] && [ ! -d /etc/resolvconf/run ] ; then
		report_info "Deleting /etc/resolvconf/run which isn't a directory"
		rm -f /etc/resolvconf/run
	fi

	# OK, now /etc/resolvconf/run is either:
	# * nonexistent, or
	# * a dangling but canonicalizable symlink, or
	# * a symlink to a directory, or
	# * a directory

	# Create subdirectory
	if [ -d /etc/resolvconf/run ] ; then
		# It's a directory or a symlink to one
		[ -d /etc/resolvconf/run/interface ] || mkdir -v /etc/resolvconf/run/interface
	elif [ -L /etc/resolvconf/run ] ; then
		# It's a dangling but canonicalizable symlink
		mkdir -v "$RUN_CANONICALPATH" "${RUN_CANONICALPATH}/interface"
	else
		# It's nonexistent

		if standard_run_available && standard_run_subdirs_exist_or_create ; then
			ln -s /run/resolvconf /etc/resolvconf/run
		else
			mkdir -v /etc/resolvconf/run /etc/resolvconf/run/interface
		fi
	fi
	;;
  # abort-upgrade)
	# Don't do anything because we don't anything in the postrm on upgrade or failed-upgrade
	# ;;
esac

#DEBHELPER#

db_stop

