#!/bin/sh
set -e

case "$1" in
  remove)
	if [ -x "/etc/init.d/resolvconf" ] ; then
		if which invoke-rc.d >/dev/null 2>&1 ; then
			invoke-rc.d resolvconf disable-updates || :
		else
			/etc/init.d/resolvconf disable-updates
		fi
	fi							
	;;
  # deconfigure)
	# This code path should not be used.
	# N.B.: Other packages should not declare "Breaks: resolvconf";
	# they should declare "Conflicts: resolvconf" instead.
	# ;;
  # upgrade|failed-upgrade)
	# Don't do anything
	# ;;
esac

#DEBHELPER#

