#!/bin/sh
set -e

case "$1" in
  remove)
	if [ -x /etc/init.d/resolvconf ] ; then
		/etc/init.d/resolvconf disable-updates
	fi							
	;;
  # deconfigure)
	# This code path should not be used.
	# N.B.: Other packages should not declare "Breaks: resolvconf";
	# they should declare "Conflicts: resolvconf" instead.
	# ;;
  # upgrade|failed-upgrade)
	# Don't do anything
	# ;;
esac

#DEBHELPER#

exit 0
