#!/bin/sh

set -e

disable_updates() {
	if which invoke-rc.d >/dev/null 2>&1 ; then
		invoke-rc.d resolvconf disable-updates || :
	else
		! [ -x /etc/init.d/resolvconf ] || /etc/init.d/resolvconf disable-updates
	fi
}

case "$1" in
  remove)
	disable-updates
	;;
  # deconfigure)
	# This code path should not be used.
	# N.B.: Other packages should not declare "Breaks: resolvconf";
	# they should declare "Conflicts: resolvconf" instead.
	# ;;
  # upgrade|failed-upgrade)
	# Don't do anything
	# ;;
esac

#DEBHELPER#

exit 0
